# Generated by Django 6.0.8 on 2026-08-08 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name for this service (e.g., "MyFinder Database")', max_length=255)),
                ('provider', models.CharField(choices=[('AIVEN', 'Aiven'), ('AWS', 'AWS'), ('GCP', 'Google Cloud'), ('AZURE', 'Azure'), ('SELF_HOSTED', 'Self-Hosted'), ('OTHER', 'Other')], default='AIVEN', help_text='Cloud provider hosting this service', max_length=20)),
                ('service_type', models.CharField(choices=[('POSTGRESQL', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('REDIS', 'Redis'), ('REST_API', 'REST API'), ('WEBSITE', 'Website')], default='POSTGRESQL', help_text='Type of service to monitor', max_length=20)),
                ('host', models.CharField(help_text='Hostname (e.g., myproject.aivencloud.com)', max_length=255)),
                ('port', models.IntegerField(help_text='Port number (e.g., 21699 for Aiven)')),
                ('database_name', models.CharField(blank=True, default='', help_text='Database name (for PostgreSQL/MySQL)', max_length=255)),
                ('encrypted_username', models.TextField(blank=True, default='', help_text='Encrypted username for authentication')),
                ('encrypted_password', models.TextField(blank=True, default='', help_text='Encrypted password for authentication')),
                ('ssl_mode', models.CharField(default='require', help_text='SSL mode (require, disable, etc.)', max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable monitoring for this service')),
                ('check_interval', models.IntegerField(default=300, help_text='Health check interval in seconds (default: 5 minutes)')),
                ('current_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy'), ('UNKNOWN', 'Unknown'), ('DISABLED', 'Disabled')], default='UNKNOWN', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Timestamp of the last health check', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
