# Generated by Django 6.0.8 on 2026-08-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the check failed')),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='When the check was performed')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='services.service')),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('reason', models.TextField(help_text='Reason for the incident (e.g., error message from checks)')),
                ('started_at', models.DateTimeField(help_text='When the incident started (first failed check)')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the service recovered', null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='services.service')),
                ('triggering_checks', models.ManyToManyField(blank=True, related_name='triggered_incidents', to='monitoring.healthcheck')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['service', 'checked_at'], name='monitoring__service_6735b0_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['status'], name='monitoring__status_8e51ed_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheck',
            index=models.Index(fields=['checked_at'], name='monitoring__checked_028f71_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['service', 'status'], name='monitoring__service_8a62ab_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['started_at'], name='monitoring__started_716c59_idx'),
        ),
    ]
